homepage:
  patch: /
  defaults: { _controller: AppBundel:Default:index}

dform:
  patch: /dform
  defaults: { _controller: AppBundel:Default:dform}


form_view:
  patch: /history{$id}
  defaults: { _controller: AppBundel:Default:formView}
  requirements:
    id: \d+