fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation


homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }

dform:
    path: /dform
    defaults: { _controller: AppBundle:Default:dform }

history:
    path: /history
    defaults: { _controller: AppBundle:Default:history }
