<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DForm extends \AppBundle\Entity\DForm implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'userId', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName1', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName1', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName2', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName2', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName3', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName3', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName4', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName4', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName5', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName5', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName6', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName6', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName7', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName7', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName8', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName8', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName9', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName9', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName10', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName10', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'initialDate', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'initialTime', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'endingDate', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'endingTime'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'userId', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName1', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName1', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName2', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName2', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName3', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName3', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName4', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName4', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName5', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName5', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName6', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName6', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName7', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName7', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName8', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName8', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName9', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName9', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'firstName10', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'lastName10', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'initialDate', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'initialTime', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'endingDate', '' . "\0" . 'AppBundle\\Entity\\DForm' . "\0" . 'endingTime'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DForm $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$userId]);

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle($title = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', [$title]);

        return parent::getTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', [$firstName]);

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName($firstName = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', [$firstName]);

        return parent::getFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', [$lastName]);

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName($lastName = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', [$lastName]);

        return parent::getLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName1($firstName1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName1', [$firstName1]);

        return parent::setFirstName1($firstName1);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName1($firstName1 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName1', [$firstName1]);

        return parent::getFirstName1($firstName1);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName1($lastName1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName1', [$lastName1]);

        return parent::setLastName1($lastName1);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName1($lastName1 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName1', [$lastName1]);

        return parent::getLastName1($lastName1);
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName2($firstName2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName2', [$firstName2]);

        return parent::setFirstName2($firstName2);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName2($firstName2 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName2', [$firstName2]);

        return parent::getFirstName2($firstName2);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName2($lastName2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName2', [$lastName2]);

        return parent::setLastName2($lastName2);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName2($lastName2 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName2', [$lastName2]);

        return parent::getLastName2($lastName2);
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName3($firstName3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName3', [$firstName3]);

        return parent::setFirstName3($firstName3);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName3($firstName3 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName3', [$firstName3]);

        return parent::getFirstName3($firstName3);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName3($lastName3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName3', [$lastName3]);

        return parent::setLastName3($lastName3);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName3($lastName3 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName3', [$lastName3]);

        return parent::getLastName3($lastName3);
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName4($firstName4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName4', [$firstName4]);

        return parent::setFirstName4($firstName4);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName4($firstName4 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName4', [$firstName4]);

        return parent::getFirstName4($firstName4);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName4($lastName4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName4', [$lastName4]);

        return parent::setLastName4($lastName4);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName4($lastName4 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName4', [$lastName4]);

        return parent::getLastName4($lastName4);
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName5($firstName5)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName5', [$firstName5]);

        return parent::setFirstName5($firstName5);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName5($firstName5 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName5', [$firstName5]);

        return parent::getFirstName5($firstName5);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName5($lastName5)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName5', [$lastName5]);

        return parent::setLastName5($lastName5);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName5($lastName5 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName5', [$lastName5]);

        return parent::getLastName5($lastName5);
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName6($firstName6)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName6', [$firstName6]);

        return parent::setFirstName6($firstName6);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName6($firstName6 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName6', [$firstName6]);

        return parent::getFirstName6($firstName6);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName6($lastName6)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName6', [$lastName6]);

        return parent::setLastName6($lastName6);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName6($lastName6 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName6', [$lastName6]);

        return parent::getLastName6($lastName6);
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName7($firstName7)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName7', [$firstName7]);

        return parent::setFirstName7($firstName7);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName7($firstName7 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName7', [$firstName7]);

        return parent::getFirstName7($firstName7);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName7($lastName7)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName7', [$lastName7]);

        return parent::setLastName7($lastName7);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName7($lastName7 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName7', [$lastName7]);

        return parent::getLastName7($lastName7);
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName8($firstName8)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName8', [$firstName8]);

        return parent::setFirstName8($firstName8);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName8($firstName8 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName8', [$firstName8]);

        return parent::getFirstName8($firstName8);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName8($lastName8)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName8', [$lastName8]);

        return parent::setLastName8($lastName8);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName8($lastName8 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName8', [$lastName8]);

        return parent::getLastName8($lastName8);
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName9($firstName9)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName9', [$firstName9]);

        return parent::setFirstName9($firstName9);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName9($firstName9 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName9', [$firstName9]);

        return parent::getFirstName9($firstName9);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName9($lastName9)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName9', [$lastName9]);

        return parent::setLastName9($lastName9);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName9($lastName9 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName9', [$lastName9]);

        return parent::getLastName9($lastName9);
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName10($firstName10)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName10', [$firstName10]);

        return parent::setFirstName10($firstName10);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName10($firstName10 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName10', [$firstName10]);

        return parent::getFirstName10($firstName10);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName10($lastName10)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName10', [$lastName10]);

        return parent::setLastName10($lastName10);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName10($lastName10 = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName10', [$lastName10]);

        return parent::getLastName10($lastName10);
    }

    /**
     * {@inheritDoc}
     */
    public function setInitialDate($initialDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInitialDate', [$initialDate]);

        return parent::setInitialDate($initialDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getInitialDate($initialDate = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInitialDate', [$initialDate]);

        return parent::getInitialDate($initialDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setInitialTime($initialTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInitialTime', [$initialTime]);

        return parent::setInitialTime($initialTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getInitialTime($initialTime = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInitialTime', [$initialTime]);

        return parent::getInitialTime($initialTime);
    }

    /**
     * {@inheritDoc}
     */
    public function setEndingDate($endingDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndingDate', [$endingDate]);

        return parent::setEndingDate($endingDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndingDate($endingDate = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndingDate', [$endingDate]);

        return parent::getEndingDate($endingDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setEndingTime($endingTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndingTime', [$endingTime]);

        return parent::setEndingTime($endingTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndingTime($endingTime = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndingTime', [$endingTime]);

        return parent::getEndingTime($endingTime);
    }

}
